version: '3.8'
services:
  alcity_mgm_api:
    build: .
    image: 'alcity_management_system'
    ports:
      - "8080:8080"
    depends_on:
      -   alcity_mgm_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.17.0.1:5432/alcity_management_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  alcity_mgm_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alcity_management_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"